title: Myriad System Documentation
description: Documentation pages for splitkb.com's Myriad System
theme: just-the-docs

url: https://myriad.splitkb.com

# Branding
logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red
